version: '3.6'
services:
  bitespeed:
    image: docker.bitespeed
    container_name: bitespeed-container
    ports:
      - "8000:8000"
    restart: always
    networks:
      - lb_net
        
networks:
  lb_net:
    name: lb_net
    external: true
    

    
